#!/usr/bin/env bash
# Kernel development pipeline driver. See PIPELINE.md.
#
#   ./pipeline.sh gt       <op>   regenerate ground truth  -> data/<op>/<op>.safetensors
#   ./pipeline.sh check    <op>   mapping/shape errors only (typecheck backend, fast)
#   ./pipeline.sh test     <op>   numeric compare vs ground truth (emulation backend)
#   ./pipeline.sh schedule <op>   compile + dump schedule  -> results/<op>/schedule.json
#   ./pipeline.sh report   <op>   write results/<op>/report.md from the last run
#   ./pipeline.sh all      <op>   gt -> check -> test -> schedule -> report
#   ./pipeline.sh ladder          run `all` for every op listed in OPS
#
# Exit code is non-zero if any step fails, so this is CI-usable as-is.

set -uo pipefail
cd "$(dirname "$0")"

# Rungs currently under the pipeline, in ladder order.
OPS=(add mul dot gemv gemm reduce_sum reduce_sum_ragged reduce_sum_exp rmsnorm softmax)

# Locate the torch venv by walking up from this package, so the package can sit at any
# depth (e.g. nested inside the cluster-image repo). Absolute path, otherwise python
# warns about an unexpected sys.prefix.
PY=""
d=$(pwd)
while [ "$d" != "/" ]; do
    [ -x "$d/.venv/bin/python" ] && { PY="$d/.venv/bin/python"; break; }
    d=$(dirname "$d")
done
[ -n "$PY" ] || PY=$(command -v python3 || command -v python)
[ -x "$PY" ] || { echo "no python with torch/safetensors found (looked for .venv upward)" >&2; exit 2; }

c_ok=$'\033[32m'; c_no=$'\033[31m'; c_dim=$'\033[2m'; c_off=$'\033[0m'
step() { printf '\n%s==> %s%s\n' "$c_dim" "$*" "$c_off"; }
ok()   { printf '%s  ok%s  %s\n' "$c_ok" "$c_off" "$*"; }
fail() { printf '%sfail%s  %s\n' "$c_no" "$c_off" "$*"; }

# Where a rung's artefacts live.
kernel_fn() { echo "ops::${1}::${1}_kernel"; }   # e.g. ops::add::add_kernel
test_target() { echo "op_${1}"; }                # tests/op_add.rs

need_op() {
    [ -n "${1:-}" ] || { echo "usage: $0 <cmd> <op>   (ops: ${OPS[*]})" >&2; exit 2; }
    [ -d "src/ops/$1" ] || { echo "no such op: src/ops/$1" >&2; exit 2; }
}

do_gt() {
    local op=$1 gt="src/ops/$1/ground_truth.py"
    step "ground truth: $op"
    [ -f "$gt" ] || { fail "missing $gt"; return 1; }
    "$PY" "$gt" && ok "ground truth" || { fail "ground truth"; return 1; }
}

do_check() {
    local op=$1
    step "typecheck: $op   (mapping/shape only)"
    if cargo furiosa-opt --backend typecheck test --release --test "$(test_target "$op")" \
        -- --nocapture 2>&1 | tail -25; then
        ok "typecheck"
    else
        fail "typecheck"; return 1
    fi
}

do_test() {
    local op=$1
    step "test: $op   (emulation backend, numeric)"
    mkdir -p "results/$op"
    if cargo furiosa-opt test --release --test "$(test_target "$op")" \
        -- --nocapture 2>&1 | tee "results/$op/test.log" | tail -25; then
        ok "test"
    else
        fail "test"; return 1
    fi
}

do_schedule() {
    local op=$1 fn; fn=$(kernel_fn "$op")
    step "schedule: $op   ($fn)"
    mkdir -p "results/$op"
    rm -f "results/$op/schedule.json"
    # `compile` always builds NPU kernels. The schedule is dumped *before* the final
    # LIR -> C -> object step, so the json can be valid even when `compile` exits
    # non-zero (e.g. an incomplete host libc6-dev). Judge on the artefact, not the
    # exit code. Non-fatal either way.
    cargo furiosa-opt compile "$fn" --dump-schedule "results/$op/schedule.json" \
        > "results/$op/schedule.log" 2>&1
    if [ -s "results/$op/schedule.json" ]; then
        ok "schedule -> results/$op/schedule.json ($(wc -c < "results/$op/schedule.json") bytes)"
        grep -q "^error" "results/$op/schedule.log" &&
            printf '%s      (codegen after the dump failed; see schedule.log)%s\n' "$c_dim" "$c_off"
    else
        fail "schedule not produced (see results/$op/schedule.log)"
    fi
}

do_report() {
    local op=$1 out="results/$1/report.md"
    step "report: $op"
    mkdir -p "results/$op"
    {
        echo "# $op — run report"
        echo
        echo "Generated by \`pipeline.sh report $op\`. Re-run with \`./pipeline.sh all $op\`."
        echo
        echo "## Result"
        echo
        if grep -q "test result: ok" "results/$op/test.log" 2>/dev/null; then
            echo "- **PASS** against \`data/$op/$op.safetensors\`"
        elif [ -f "results/$op/test.log" ]; then
            echo "- **FAIL** — see \`test.log\`"
        else
            echo "- not run"
        fi
        if [ -f "results/$op/test.log" ]; then
            echo
            echo '```'
            grep -E "^test |test result:|max abs diff|panicked at|Expected|got" \
                "results/$op/test.log" 2>/dev/null | head -20
            echo '```'
        fi
        echo
        echo "## Schedule"
        echo
        if [ -s "results/$op/schedule.json" ]; then
            echo "- \`results/$op/schedule.json\` — open with \`furiosa-schedule-viewer\`"
            echo "- size: $(wc -c < "results/$op/schedule.json") bytes"
        else
            echo "- not produced (see \`schedule.log\`; \`compile\` needs the NPU toolchain)"
        fi
        echo
        echo "## Sources"
        echo
        echo "- kernel: \`src/ops/$op/mod.rs\`"
        echo "- spec: \`src/ops/$op/spec.md\`"
        echo "- ground truth: \`src/ops/$op/ground_truth.py\`"
        echo "- test: \`tests/op_$op.rs\`"
        echo
        echo "## Observations"
        echo
        echo "<!-- fill in by hand: cycles, bottleneck, what you'd change -->"
    } > "$out"
    ok "report -> $out"
}

do_all() {
    local op=$1 rc=0
    do_gt "$op"       || rc=1
    do_check "$op"    || rc=1
    do_test "$op"     || rc=1
    do_schedule "$op"          # non-fatal
    do_report "$op"
    return $rc
}

cmd=${1:-}; shift || true
case "$cmd" in
    gt)       need_op "${1:-}"; do_gt "$1" ;;
    check)    need_op "${1:-}"; do_check "$1" ;;
    test)     need_op "${1:-}"; do_test "$1" ;;
    schedule) need_op "${1:-}"; do_schedule "$1" ;;
    report)   need_op "${1:-}"; do_report "$1" ;;
    all)      need_op "${1:-}"; do_all "$1" ;;
    ladder)
        rc=0
        for op in "${OPS[@]}"; do do_all "$op" || rc=1; done
        step "ladder complete"
        for op in "${OPS[@]}"; do
            if grep -q "test result: ok" "results/$op/test.log" 2>/dev/null; then
                ok "$op"
            else
                fail "$op"
            fi
        done
        exit $rc ;;
    *) sed -n '2,20p' "$0" >&2; exit 2 ;;
esac
